const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const C=require('../src/core.cjs');const {Ledger}=require('../src/ledger.cjs');
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'human-mining-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return path.join(dir,'blockchain.jsonl');}
const alice='00100001',bob='00100002',miner='00100003';
function solve(l){const b=l.pending;for(let n=0;n<10000;n++){const nonce=String(n).padStart(4,'0'),hash=C.hash(C.payload(b,nonce));if(Number(hash)<b.difficulty)return {token:b.token,nonce,hash};}throw Error('no solution');}
function mine(l,who=alice){l.prepare({type:'reward',miner:who});l.submit(solve(l));}
test('30桁・手計算の既知値・金額とIDの検証',()=>{assert.equal(C.hash('00000'.repeat(5)+'00001'),'0001');assert.equal(C.hash('01234'+'00000'.repeat(5)),'5227');assert.equal(C.units('12.4'),124);for(const x of ['-1','1.22','NaN','100000'])assert.throws(()=>C.units(x));assert.throws(()=>C.id('00000000'));assert.throws(()=>C.id(12345678));});
test('新規発行→送金→再起動で全残高復元',t=>{const file=setup(t),l=new Ledger(file);mine(l);mine(l);l.prepare({type:'transfer',from:alice,to:bob,amount:'1.5',miner});assert.equal(C.payload(l.pending,'0000').length,30);l.submit(solve(l));assert.equal(l.s.bank[alice],3);assert.equal(l.s.bank[bob],15);assert.equal(l.s.bank[miner],12);assert.deepEqual(new Ledger(file).s,l.s);assert.equal(Object.values(l.s.bank).reduce((a,b)=>a+b,0),30);});
test('残高不足・誤答・古い課題・二重確定を拒否',t=>{const l=new Ledger(setup(t));assert.throws(()=>l.prepare({type:'transfer',from:alice,to:bob,amount:'1',miner}));l.prepare({type:'reward',miner:alice});const good=solve(l);assert.throws(()=>l.submit({...good,hash:'xxxx'}));assert.equal(l.s.blocks.length,1);l.submit(good);assert.throws(()=>l.submit(good));l.prepare({type:'reward',miner});assert.throws(()=>l.submit(good));});
test('同じIDが送受信・採掘を兼ねても正しく精算',t=>{const l=new Ledger(setup(t));mine(l);l.prepare({type:'transfer',from:alice,to:alice,amount:'0.8',miner:alice});l.submit(solve(l));assert.equal(l.s.bank[alice],20);});
test('設定は課題中固定・過去の報酬を変更しない',t=>{const file=setup(t),l=new Ledger(file);mine(l);l.configure({difficulty:10000,reward:25});l.prepare({type:'reward',miner:alice});assert.throws(()=>l.configure(C.DEFAULTS));l.submit(solve(l));const restarted=new Ledger(file);assert.equal(restarted.s.bank[alice],35);assert.equal(restarted.config.reward,25);});
test('未完了末尾をバックアップして復旧、次の追記も正常',t=>{const file=setup(t),l=new Ledger(file);mine(l);const valid=fs.readFileSync(file);fs.appendFileSync(file,'{"index":2');const restored=new Ledger(file);assert.match(restored.warning,/復旧/);assert.deepEqual(fs.readFileSync(file),valid);assert.equal(fs.readdirSync(path.dirname(file)).filter(f=>f.endsWith('.bak')).length,1);mine(restored,bob);assert.equal(new Ledger(file).s.blocks.length,3);});
test('末尾改行のない完全JSONも未確定として退避',t=>{const file=setup(t),l=new Ledger(file);mine(l);const bytes=fs.readFileSync(file);fs.writeFileSync(file,bytes.subarray(0,-1));assert.equal(new Ledger(file).s.blocks.length,1);});
test('台帳途中の破損は原本を変更せず停止',t=>{const file=setup(t),l=new Ledger(file);mine(l);const lines=fs.readFileSync(file,'utf8').trim().split('\n');const b=JSON.parse(lines[1]);b.hash='xxxx';lines[1]=JSON.stringify(b);fs.writeFileSync(file,lines.join('\n')+'\nunfinished');const before=fs.readFileSync(file);assert.throws(()=>new Ledger(file),/2行目/);assert.deepEqual(fs.readFileSync(file),before);});
test('fsync失敗時はbank更新せず、そのセッションの追記を停止',t=>{const file=setup(t),l=new Ledger(file);l.prepare({type:'reward',miner:alice});const good=solve(l);l.io={...fs,fsyncSync(){throw Error('injected');}};assert.throws(()=>l.submit(good),/保存に失敗/);assert.equal(l.s.bank[alice],0);assert.equal(l.s.blocks.length,1);assert.throws(()=>l.submit(good),/再起動/);assert.equal(new Ledger(file).s.bank[alice],10);});
test('部分書き込みを繰り返して完全な1行を保存',t=>{const file=setup(t),l=new Ledger(file);l.io={...fs,writeSync(fd,b,offset,length){return fs.writeSync(fd,b,offset,Math.min(length,7));}};mine(l);assert.equal(new Ledger(file).s.bank[alice],10);});
test('100回の採掘で整数残高・連鎖・保存を確認',t=>{const file=setup(t),l=new Ledger(file);for(let i=0;i<100;i++)mine(l,i%2?alice:bob);const r=new Ledger(file);assert.equal(r.s.bank[alice],500);assert.equal(r.s.bank[bob],500);});
